- hosts: servers
  remote_user: root
  tasks:
 #   - name: Insrtall mysql 5.7 repo
 #     yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present 
   
 #   - name: Install mysql 5.7
 #     yum: pkg={{ item }}
 #     with_items:
 #     - mysql-community-server
 #     - mysql-community-client
 #     - MySQL-python
   
 #   - name: Strat the MYSQL service
   
     - name: Change mysql root password and keep track in 
       shell: |
         password_match=`awk '/A temporary password is generated for/ {a=$0} END{ print a }' /var/log/mysqld.log | awk '{print $(NF)}'`
         echo $password_match
         mysql -uroot -p$password_match --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '5ekdsci6pa%L1'; flush privileges; "
         echo "[client]"
         user=root
         password=5ekdsci6pa%L1  > /root/.my.cnf
       args:
         creates: /root/.my.cnf
       register: change_temp_pass
       notify: restart mysqld

     - meta: flush_handlers
     - debug:
         var: change_temp_pass
  handlers:
    - name: restart mysqld
      service: name=mysqld 
               enabled=yes    
               state=restarted
      #   state: restartervice: name=mysqld state=started

