
- hosts: servers
  remote_user: root
  tasks:
  - name: Add repo for NGINX
    yum: name=epel-release state=present
  - name: install nginx
    yum: name=nginx state=present
#  - name: insert index page
#    template:
#     src: index.html
#     dest: /usr/share/nginx/html/index.html
  - name:  Start nginx after install
    service: name=nginx state=started
  - name: Create Nginx virtual host
    template:
    src: vhost.j2
    dest: /etc/nginx/sites-enabled/vhost-{{ vps2.hieutranqn.info }}
    notify: restart nginx 
